-- MySQL Script generated by MySQL Workbench
-- Mon Aug  9 14:00:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `Patient ID` INT NOT NULL,
  `age` INT NULL,
  `gender` CHAR NULL,
  `ethnic` CHAR NULL,
  `history` VARCHAR(45) NULL,
  PRIMARY KEY (`Patient ID`),
  UNIQUE INDEX `idPatient_UNIQUE` (`Patient ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Blood_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Blood_test` (
  `Patient_Patient ID` INT NOT NULL,
  `WBC` DECIMAL NULL,
  `RBC` DECIMAL NULL,
  `HGB` DECIMAL NULL,
  `HCT` DECIMAL NULL,
  `PLT` DECIMAL NULL,
  `MPV` DECIMAL NULL,
  `IG#` DECIMAL NULL,
  `IG%` DECIMAL NULL,
  `MCH` DECIMAL NULL,
  `NEUT#` DECIMAL NULL,
  `LYMPH` DECIMAL NULL,
  `MONO#` DECIMAL NULL,
  `EO#` DECIMAL NULL,
  `BASO#` DECIMAL NULL,
  `NEUT%` DECIMAL NULL,
  `LYMPH` DECIMAL NULL,
  `MONO%` DECIMAL NULL,
  `EO%` DECIMAL NULL,
  `BASO%` DECIMAL NULL,
  `RDW-S` DECIMAL NULL,
  `RDW-C` DECIMAL NULL,
  `PDW` DECIMAL NULL,
  `MCV` DECIMAL NULL,
  `P-LCR` DECIMAL NULL,
  `MCHC` DECIMAL NULL,
  `PCT` DECIMAL NULL,
  `NRBC%` DECIMAL NULL,
  `NRBC#` DECIMAL NULL,
  `P-LCC` DECIMAL NULL,
  PRIMARY KEY (`Patient_Patient ID`),
  INDEX `fk_blood test_Patient1_idx` (`Patient_Patient ID` ASC) VISIBLE,
  CONSTRAINT `fk_blood test_Patient1`
    FOREIGN KEY (`Patient_Patient ID`)
    REFERENCES `mydb`.`Patient` (`Patient ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Liver_function_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Liver_function_test` (
  `Patient_Patient ID` INT NOT NULL,
  `AST` DECIMAL NULL,
  `ALT` DECIMAL NULL,
  `TP` DECIMAL NULL,
  `ALB` DECIMAL NULL,
  `GLB` DECIMAL NULL,
  `A/G` DECIMAL NULL,
  `TBIL` DECIMAL NULL,
  `DBIL` DECIMAL NULL,
  `IB` DECIMAL NULL,
  `TBA` DECIMAL NULL,
  `LDH` DECIMAL NULL,
  `CK` DECIMAL NULL,
  `CKI` DECIMAL NULL,
  `Mb` DECIMAL NULL,
  `CRP` DECIMAL NULL,
  `P` DECIMAL NULL,
  `K` DECIMAL NULL,
  `Na` DECIMAL NULL,
  `Cl` DECIMAL NULL,
  `Ca` DECIMAL NULL,
  `GLU` DECIMAL NULL,
  `UREA` DECIMAL NULL,
  `CR` DECIMAL NULL,
  `UA` DECIMAL NULL,
  `TG` DECIMAL NULL,
  `CHO` DECIMAL NULL,
  `HDL-C` DECIMAL NULL,
  `LDL` DECIMAL NULL,
  `APOA1` DECIMAL NULL,
  `APOB` DECIMAL NULL,
  PRIMARY KEY (`Patient_Patient ID`),
  CONSTRAINT `fk_Liver function test_Patient1`
    FOREIGN KEY (`Patient_Patient ID`)
    REFERENCES `mydb`.`Patient` (`Patient ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disease` (
  `Disease Short` VARCHAR(5) NOT NULL,
  `Disease Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Disease Short`),
  UNIQUE INDEX `Disease Name_UNIQUE` (`Disease Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnosis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagnosis` (
  `Patient_Patient ID` INT NOT NULL,
  PRIMARY KEY (`Patient_Patient ID`),
  CONSTRAINT `fk_Diagnosis_Patient1`
    FOREIGN KEY (`Patient_Patient ID`)
    REFERENCES `mydb`.`Patient` (`Patient ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Physical_examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Physical_examination` (
  `Patient_Patient ID` INT NOT NULL,
  `T` VARCHAR(10) NULL,
  `P` VARCHAR(10) NULL,
  `R` VARCHAR(10) NULL,
  `BP` VARCHAR(10) NULL,
  PRIMARY KEY (`Patient_Patient ID`),
  CONSTRAINT `fk_Physical examination_Patient1`
    FOREIGN KEY (`Patient_Patient ID`)
    REFERENCES `mydb`.`Patient` (`Patient ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnosis_has_Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagnosis_has_Disease` (
  `Diagnosis_Patient_Patient ID` INT NOT NULL,
  `Disease_Disease Short` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Diagnosis_Patient_Patient ID`, `Disease_Disease Short`),
  INDEX `fk_Diagnosis_has_Disease_Disease1_idx` (`Disease_Disease Short` ASC) VISIBLE,
  INDEX `fk_Diagnosis_has_Disease_Diagnosis1_idx` (`Diagnosis_Patient_Patient ID` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnosis_has_Disease_Diagnosis1`
    FOREIGN KEY (`Diagnosis_Patient_Patient ID`)
    REFERENCES `mydb`.`Diagnosis` (`Patient_Patient ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagnosis_has_Disease_Disease1`
    FOREIGN KEY (`Disease_Disease Short`)
    REFERENCES `mydb`.`Disease` (`Disease Short`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
